const LinkedList = require('../5.linkedlist')

const ll = new LinkedList()
ll.add('lzx')
ll.add('hhh')
ll.add('iii')
ll.add('jjj')
ll.add('kkk')
ll.add('lll')
ll.add('mmm')

console.log(ll)
console.log(ll.size())

console.log(ll.findElementAt(3))
ll.removeAt(3)
console.log(ll.findElementAt(3))
ll.addAt(3, 'zzz')
console.log(ll.findElementAt(3))
console.log(ll.size())
ll.remove('mmm')
console.log(ll.findElementAt(5))
console.log(ll)
ll.remove('lzx')
console.log(ll)
console.log(ll.toString())
